# Maps commonly traded NSE symbols to sectors.
# Unknown symbols default to 'Unknown'.

NSE_SECTOR_MAPPING = {
    "ADANIENT": "Industrials",
    "ADANIGREEN": "Utilities",
    "ADANIPORTS": "Industrials",
    "ADANIPOWER": "Utilities",
    "AMBUJACEM": "Materials",
    "APOLLOHOSP": "Healthcare",
    "APOLLOTYRE": "Automobile",
    "ASHOKLEY": "Automobile",
    "ASIANPAINT": "Materials",
    "AUROPHARMA": "Healthcare",
    "AXISBANK": "Financial Services",
    "BAJAJ-AUTO": "Automobile",
    "BAJAJFINSV": "Financial Services",
    "BAJFINANCE": "Financial Services",
    "BANDHANBNK": "Financial Services",
    "BANKBARODA": "Financial Services",
    "BEL": "Industrials",
    "BHARATFORG": "Industrials",
    "BHARTIARTL": "Telecommunication",
    "BHEL": "Industrials",
    "BIOCON": "Healthcare",
    "BOSCHLTD": "Automobile",
    "BPCL": "Energy",
    "BRITANNIA": "Consumer Staples",
    "CANBK": "Financial Services",
    "CIPLA": "Healthcare",
    "COALINDIA": "Energy",
    "COLPAL": "Consumer Staples",
    "CONCOR": "Industrials",
    "DABUR": "Consumer Staples",
    "DIVISLAB": "Healthcare",
    "DLF": "Real Estate",
    "DMART": "Consumer Staples",
    "DRREDDY": "Healthcare",
    "EICHERMOT": "Automobile",
    "GAIL": "Energy",
    "GODREJCP": "Consumer Staples",
    "GRASIM": "Materials",
    "HAL": "Industrials",
    "HAVELLS": "Industrials",
    "HCLTECH": "Information Technology",
    "HDFCBANK": "Financial Services",
    "HDFCLIFE": "Financial Services",
    "HEROMOTOCO": "Automobile",
    "HINDALCO": "Materials",
    "HINDUNILVR": "Consumer Staples",
    "ICICIBANK": "Financial Services",
    "ICICIGI": "Financial Services",
    "ICICIPRULI": "Financial Services",
    "IDEA": "Telecommunication",
    "INDIGO": "Industrials",
    "INDUSINDBK": "Financial Services",
    "INFY": "Information Technology",
    "IOC": "Energy",
    "IRCTC": "Consumer Discretionary",
    "IRFC": "Financial Services",
    "ITC": "Consumer Staples",
    "JINDALSTEL": "Materials",
    "JSWENERGY": "Utilities",
    "JSWSTEEL": "Materials",
    "JUBLFOOD": "Consumer Discretionary",
    "KOTAKBANK": "Financial Services",
    "LICHSGFIN": "Financial Services",
    "LT": "Industrials",
    "LTIM": "Information Technology",
    "LTTS": "Information Technology",
    "LUPIN": "Healthcare",
    "M&M": "Automobile",
    "MANKIND": "Healthcare",
    "MARICO": "Consumer Staples",
    "MARUTI": "Automobile",
    "MFSL": "Financial Services",
    "MOTHERSON": "Automobile",
    "MPHASIS": "Information Technology",
    "NAUKRI": "Communication Services",
    "NESTLEIND": "Consumer Staples",
    "NHPC": "Utilities",
    "NMDC": "Materials",
    "NTPC": "Utilities",
    "OBEROIRLTY": "Real Estate",
    "OFSS": "Information Technology",
    "ONGC": "Energy",
    "PAGEIND": "Consumer Discretionary",
    "PAYTM": "Financial Services",
    "PEL": "Financial Services",
    "PERSISTENT": "Information Technology",
    "PETRONET": "Energy",
    "PIDILITIND": "Materials",
    "PNB": "Financial Services",
    "POLYCAB": "Industrials",
    "POWERGRID": "Utilities",
    "PVRINOX": "Consumer Discretionary",
    "RAMCOCEM": "Materials",
    "RECLTD": "Financial Services",
    "RELIANCE": "Energy",
    "SAIL": "Materials",
    "SBICARD": "Financial Services",
    "SBILIFE": "Financial Services",
    "SBIN": "Financial Services",
    "SHREECEM": "Materials",
    "SIEMENS": "Industrials",
    "SRF": "Chemicals",
    "SUNPHARMA": "Healthcare",
    "SUZLON": "Industrials",
    "TATACHEM": "Chemicals",
    "TATACOMM": "Telecommunication",
    "TATACONSUM": "Consumer Staples",
    "TATAMOTORS": "Automobile",
    "TATAPOWER": "Utilities",
    "TATASTEEL": "Materials",
    "TCS": "Information Technology",
    "TECHM": "Information Technology",
    "TITAN": "Consumer Discretionary",
    "TORNTPHARM": "Healthcare",
    "TORNTPOWER": "Utilities",
    "TRENT": "Consumer Discretionary",
    "TVSMOTOR": "Automobile",
    "ULTRACEMCO": "Materials",
    "UNIONBANK": "Financial Services",
    "UPL": "Chemicals",
    "VEDL": "Materials",
    "VOLTAS": "Consumer Discretionary",
    "WIPRO": "Information Technology",
    "ZOMATO": "Consumer Discretionary",
    "ZYDUSLIFE": "Healthcare",
}